DROP TABLE PHONES IF EXISTS;
CREATE TABLE PHONES (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(128) NOT NULL
);

DROP TABLE RESERVATIONS IF EXISTS;
CREATE TABLE RESERVATIONS (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    phone_id INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    booked_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE RESERVATIONS ADD FOREIGN KEY (phone_id) REFERENCES PHONES(id);